server.port: 8888

spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  zipkin:
    base-url: http://localhost:9411   # Zipkin URL
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: ['refresh', 'beans', 'evn']