version: "3"
services:
  mysql:
    image: mysql:5.5
    restart: always
    container_name: mysql
    hostname: mysql
    ports:
      - "3307:3306"
    expose:
      - '3307'
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: